[package]
name = "cheetah_search_mx"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num_cpus = "1.15.0"
eframe = "0.21.3"
egui = "0.21.0"
egui_extras = "0.21.0"
rfd = "0.11.2"